"""empty message

Revision ID: 85f903fae553
Revises: 
Create Date: 2023-10-02 19:53:54.792536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f903fae553'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id_user', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario', sa.Text(), nullable=False),
    sa.Column('contraseña', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('post',
    sa.Column('id_post', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['usuario.id_user'], ),
    sa.PrimaryKeyConstraint('id_post')
    )
    op.create_table('comentarios',
    sa.Column('id_comentario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_post', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['id_post'], ['post.id_post'], ),
    sa.PrimaryKeyConstraint('id_comentario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentarios')
    op.drop_table('post')
    op.drop_table('usuario')
    # ### end Alembic commands ###
